name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-community-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-with-gh-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create comment with GH API
        run: |
          gh api -X POST \
            ${REPOSITORY}/issues/${ISSUE_NUMBER} \
            -f body='
            Comment but from the GH API call not community action'

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.event.issue.repository_url }}
          ISSUE_NUMBER: ${{ github.event.issue.number}}